/* Generated by Yosys 0.30+48 (git sha1 14d50a176d5, gcc 8.3.1 -fPIC -Os) */

module uart_tx_fifo(clk, rstn, push, pop, data_in, fifo_empty, fifo_full, count, data_out);
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  input clk;
  wire clk;
  output [4:0] count;
  wire [4:0] count;
  wire \data_fifo[0][0] ;
  wire \data_fifo[0][1] ;
  wire \data_fifo[0][2] ;
  wire \data_fifo[0][3] ;
  wire \data_fifo[0][4] ;
  wire \data_fifo[0][5] ;
  wire \data_fifo[0][6] ;
  wire \data_fifo[0][7] ;
  wire \data_fifo[10][0] ;
  wire \data_fifo[10][1] ;
  wire \data_fifo[10][2] ;
  wire \data_fifo[10][3] ;
  wire \data_fifo[10][4] ;
  wire \data_fifo[10][5] ;
  wire \data_fifo[10][6] ;
  wire \data_fifo[10][7] ;
  wire \data_fifo[11][0] ;
  wire \data_fifo[11][1] ;
  wire \data_fifo[11][2] ;
  wire \data_fifo[11][3] ;
  wire \data_fifo[11][4] ;
  wire \data_fifo[11][5] ;
  wire \data_fifo[11][6] ;
  wire \data_fifo[11][7] ;
  wire \data_fifo[12][0] ;
  wire \data_fifo[12][1] ;
  wire \data_fifo[12][2] ;
  wire \data_fifo[12][3] ;
  wire \data_fifo[12][4] ;
  wire \data_fifo[12][5] ;
  wire \data_fifo[12][6] ;
  wire \data_fifo[12][7] ;
  wire \data_fifo[13][0] ;
  wire \data_fifo[13][1] ;
  wire \data_fifo[13][2] ;
  wire \data_fifo[13][3] ;
  wire \data_fifo[13][4] ;
  wire \data_fifo[13][5] ;
  wire \data_fifo[13][6] ;
  wire \data_fifo[13][7] ;
  wire \data_fifo[14][0] ;
  wire \data_fifo[14][1] ;
  wire \data_fifo[14][2] ;
  wire \data_fifo[14][3] ;
  wire \data_fifo[14][4] ;
  wire \data_fifo[14][5] ;
  wire \data_fifo[14][6] ;
  wire \data_fifo[14][7] ;
  wire \data_fifo[15][0] ;
  wire \data_fifo[15][1] ;
  wire \data_fifo[15][2] ;
  wire \data_fifo[15][3] ;
  wire \data_fifo[15][4] ;
  wire \data_fifo[15][5] ;
  wire \data_fifo[15][6] ;
  wire \data_fifo[15][7] ;
  wire \data_fifo[1][0] ;
  wire \data_fifo[1][1] ;
  wire \data_fifo[1][2] ;
  wire \data_fifo[1][3] ;
  wire \data_fifo[1][4] ;
  wire \data_fifo[1][5] ;
  wire \data_fifo[1][6] ;
  wire \data_fifo[1][7] ;
  wire \data_fifo[2][0] ;
  wire \data_fifo[2][1] ;
  wire \data_fifo[2][2] ;
  wire \data_fifo[2][3] ;
  wire \data_fifo[2][4] ;
  wire \data_fifo[2][5] ;
  wire \data_fifo[2][6] ;
  wire \data_fifo[2][7] ;
  wire \data_fifo[3][0] ;
  wire \data_fifo[3][1] ;
  wire \data_fifo[3][2] ;
  wire \data_fifo[3][3] ;
  wire \data_fifo[3][4] ;
  wire \data_fifo[3][5] ;
  wire \data_fifo[3][6] ;
  wire \data_fifo[3][7] ;
  wire \data_fifo[4][0] ;
  wire \data_fifo[4][1] ;
  wire \data_fifo[4][2] ;
  wire \data_fifo[4][3] ;
  wire \data_fifo[4][4] ;
  wire \data_fifo[4][5] ;
  wire \data_fifo[4][6] ;
  wire \data_fifo[4][7] ;
  wire \data_fifo[5][0] ;
  wire \data_fifo[5][1] ;
  wire \data_fifo[5][2] ;
  wire \data_fifo[5][3] ;
  wire \data_fifo[5][4] ;
  wire \data_fifo[5][5] ;
  wire \data_fifo[5][6] ;
  wire \data_fifo[5][7] ;
  wire \data_fifo[6][0] ;
  wire \data_fifo[6][1] ;
  wire \data_fifo[6][2] ;
  wire \data_fifo[6][3] ;
  wire \data_fifo[6][4] ;
  wire \data_fifo[6][5] ;
  wire \data_fifo[6][6] ;
  wire \data_fifo[6][7] ;
  wire \data_fifo[7][0] ;
  wire \data_fifo[7][1] ;
  wire \data_fifo[7][2] ;
  wire \data_fifo[7][3] ;
  wire \data_fifo[7][4] ;
  wire \data_fifo[7][5] ;
  wire \data_fifo[7][6] ;
  wire \data_fifo[7][7] ;
  wire \data_fifo[8][0] ;
  wire \data_fifo[8][1] ;
  wire \data_fifo[8][2] ;
  wire \data_fifo[8][3] ;
  wire \data_fifo[8][4] ;
  wire \data_fifo[8][5] ;
  wire \data_fifo[8][6] ;
  wire \data_fifo[8][7] ;
  wire \data_fifo[9][0] ;
  wire \data_fifo[9][1] ;
  wire \data_fifo[9][2] ;
  wire \data_fifo[9][3] ;
  wire \data_fifo[9][4] ;
  wire \data_fifo[9][5] ;
  wire \data_fifo[9][6] ;
  wire \data_fifo[9][7] ;
  input [7:0] data_in;
  wire [7:0] data_in;
  output [7:0] data_out;
  wire [7:0] data_out;
  output fifo_empty;
  wire fifo_empty;
  output fifo_full;
  wire fifo_full;
  wire \ip_count[0] ;
  wire \ip_count[1] ;
  wire \ip_count[2] ;
  wire \ip_count[3] ;
  wire \op_count[0] ;
  wire \op_count[1] ;
  wire \op_count[2] ;
  wire \op_count[3] ;
  input pop;
  wire pop;
  input push;
  wire push;
  input rstn;
  wire rstn;
  sky130_fd_sc_hd__or4_2 _0430_ (
    .A(count[3]),
    .B(count[2]),
    .C(count[1]),
    .D(count[0]),
    .X(_0149_)
  );
  sky130_fd_sc_hd__or2_2 _0431_ (
    .A(count[4]),
    .B(_0149_),
    .X(_0150_)
  );
  sky130_fd_sc_hd__inv_2 _0432_ (
    .A(_0150_),
    .Y(fifo_empty)
  );
  sky130_fd_sc_hd__inv_2 _0433_ (
    .A(count[4]),
    .Y(_0151_)
  );
  sky130_fd_sc_hd__nor2_2 _0434_ (
    .A(_0151_),
    .B(_0149_),
    .Y(fifo_full)
  );
  sky130_fd_sc_hd__buf_1 _0435_ (
    .A(_0000_),
    .X(_0152_)
  );
  sky130_fd_sc_hd__buf_1 _0436_ (
    .A(_0001_),
    .X(_0153_)
  );
  sky130_fd_sc_hd__mux4_2 _0437_ (
    .A0(\data_fifo[0][0] ),
    .A1(\data_fifo[1][0] ),
    .A2(\data_fifo[2][0] ),
    .A3(\data_fifo[3][0] ),
    .S0(_0152_),
    .S1(_0153_),
    .X(_0154_)
  );
  sky130_fd_sc_hd__mux4_2 _0438_ (
    .A0(\data_fifo[4][0] ),
    .A1(\data_fifo[5][0] ),
    .A2(\data_fifo[6][0] ),
    .A3(\data_fifo[7][0] ),
    .S0(_0152_),
    .S1(_0153_),
    .X(_0155_)
  );
  sky130_fd_sc_hd__buf_1 _0439_ (
    .A(_0002_),
    .X(_0156_)
  );
  sky130_fd_sc_hd__mux2_2 _0440_ (
    .A0(_0154_),
    .A1(_0155_),
    .S(_0156_),
    .X(_0157_)
  );
  sky130_fd_sc_hd__buf_1 _0441_ (
    .A(_0000_),
    .X(_0158_)
  );
  sky130_fd_sc_hd__buf_1 _0442_ (
    .A(_0001_),
    .X(_0159_)
  );
  sky130_fd_sc_hd__mux4_2 _0443_ (
    .A0(\data_fifo[8][0] ),
    .A1(\data_fifo[9][0] ),
    .A2(\data_fifo[10][0] ),
    .A3(\data_fifo[11][0] ),
    .S0(_0158_),
    .S1(_0159_),
    .X(_0160_)
  );
  sky130_fd_sc_hd__buf_1 _0444_ (
    .A(_0000_),
    .X(_0161_)
  );
  sky130_fd_sc_hd__buf_1 _0445_ (
    .A(_0001_),
    .X(_0162_)
  );
  sky130_fd_sc_hd__mux4_2 _0446_ (
    .A0(\data_fifo[12][0] ),
    .A1(\data_fifo[13][0] ),
    .A2(\data_fifo[14][0] ),
    .A3(\data_fifo[15][0] ),
    .S0(_0161_),
    .S1(_0162_),
    .X(_0163_)
  );
  sky130_fd_sc_hd__mux2_2 _0447_ (
    .A0(_0160_),
    .A1(_0163_),
    .S(_0156_),
    .X(_0164_)
  );
  sky130_fd_sc_hd__mux2_2 _0448_ (
    .A0(_0157_),
    .A1(_0164_),
    .S(_0003_),
    .X(_0165_)
  );
  sky130_fd_sc_hd__buf_1 _0449_ (
    .A(_0165_),
    .X(data_out[0])
  );
  sky130_fd_sc_hd__mux4_2 _0450_ (
    .A0(\data_fifo[0][1] ),
    .A1(\data_fifo[1][1] ),
    .A2(\data_fifo[2][1] ),
    .A3(\data_fifo[3][1] ),
    .S0(_0152_),
    .S1(_0153_),
    .X(_0166_)
  );
  sky130_fd_sc_hd__mux4_2 _0451_ (
    .A0(\data_fifo[4][1] ),
    .A1(\data_fifo[5][1] ),
    .A2(\data_fifo[6][1] ),
    .A3(\data_fifo[7][1] ),
    .S0(_0152_),
    .S1(_0153_),
    .X(_0167_)
  );
  sky130_fd_sc_hd__mux2_2 _0452_ (
    .A0(_0166_),
    .A1(_0167_),
    .S(_0156_),
    .X(_0168_)
  );
  sky130_fd_sc_hd__mux4_2 _0453_ (
    .A0(\data_fifo[8][1] ),
    .A1(\data_fifo[9][1] ),
    .A2(\data_fifo[10][1] ),
    .A3(\data_fifo[11][1] ),
    .S0(_0158_),
    .S1(_0159_),
    .X(_0169_)
  );
  sky130_fd_sc_hd__mux4_2 _0454_ (
    .A0(\data_fifo[12][1] ),
    .A1(\data_fifo[13][1] ),
    .A2(\data_fifo[14][1] ),
    .A3(\data_fifo[15][1] ),
    .S0(_0161_),
    .S1(_0162_),
    .X(_0170_)
  );
  sky130_fd_sc_hd__mux2_2 _0455_ (
    .A0(_0169_),
    .A1(_0170_),
    .S(_0156_),
    .X(_0171_)
  );
  sky130_fd_sc_hd__mux2_2 _0456_ (
    .A0(_0168_),
    .A1(_0171_),
    .S(_0003_),
    .X(_0172_)
  );
  sky130_fd_sc_hd__buf_1 _0457_ (
    .A(_0172_),
    .X(data_out[1])
  );
  sky130_fd_sc_hd__mux4_2 _0458_ (
    .A0(\data_fifo[0][2] ),
    .A1(\data_fifo[1][2] ),
    .A2(\data_fifo[2][2] ),
    .A3(\data_fifo[3][2] ),
    .S0(_0152_),
    .S1(_0153_),
    .X(_0173_)
  );
  sky130_fd_sc_hd__mux4_2 _0459_ (
    .A0(\data_fifo[4][2] ),
    .A1(\data_fifo[5][2] ),
    .A2(\data_fifo[6][2] ),
    .A3(\data_fifo[7][2] ),
    .S0(_0158_),
    .S1(_0159_),
    .X(_0174_)
  );
  sky130_fd_sc_hd__mux2_2 _0460_ (
    .A0(_0173_),
    .A1(_0174_),
    .S(_0156_),
    .X(_0175_)
  );
  sky130_fd_sc_hd__mux4_2 _0461_ (
    .A0(\data_fifo[8][2] ),
    .A1(\data_fifo[9][2] ),
    .A2(\data_fifo[10][2] ),
    .A3(\data_fifo[11][2] ),
    .S0(_0158_),
    .S1(_0159_),
    .X(_0176_)
  );
  sky130_fd_sc_hd__mux4_2 _0462_ (
    .A0(\data_fifo[12][2] ),
    .A1(\data_fifo[13][2] ),
    .A2(\data_fifo[14][2] ),
    .A3(\data_fifo[15][2] ),
    .S0(_0161_),
    .S1(_0162_),
    .X(_0177_)
  );
  sky130_fd_sc_hd__mux2_2 _0463_ (
    .A0(_0176_),
    .A1(_0177_),
    .S(_0002_),
    .X(_0178_)
  );
  sky130_fd_sc_hd__mux2_2 _0464_ (
    .A0(_0175_),
    .A1(_0178_),
    .S(_0003_),
    .X(_0179_)
  );
  sky130_fd_sc_hd__buf_1 _0465_ (
    .A(_0179_),
    .X(data_out[2])
  );
  sky130_fd_sc_hd__mux4_2 _0466_ (
    .A0(\data_fifo[0][3] ),
    .A1(\data_fifo[1][3] ),
    .A2(\data_fifo[2][3] ),
    .A3(\data_fifo[3][3] ),
    .S0(_0152_),
    .S1(_0153_),
    .X(_0180_)
  );
  sky130_fd_sc_hd__mux4_2 _0467_ (
    .A0(\data_fifo[4][3] ),
    .A1(\data_fifo[5][3] ),
    .A2(\data_fifo[6][3] ),
    .A3(\data_fifo[7][3] ),
    .S0(_0158_),
    .S1(_0159_),
    .X(_0181_)
  );
  sky130_fd_sc_hd__mux2_2 _0468_ (
    .A0(_0180_),
    .A1(_0181_),
    .S(_0156_),
    .X(_0182_)
  );
  sky130_fd_sc_hd__mux4_2 _0469_ (
    .A0(\data_fifo[8][3] ),
    .A1(\data_fifo[9][3] ),
    .A2(\data_fifo[10][3] ),
    .A3(\data_fifo[11][3] ),
    .S0(_0158_),
    .S1(_0159_),
    .X(_0183_)
  );
  sky130_fd_sc_hd__mux4_2 _0470_ (
    .A0(\data_fifo[12][3] ),
    .A1(\data_fifo[13][3] ),
    .A2(\data_fifo[14][3] ),
    .A3(\data_fifo[15][3] ),
    .S0(_0161_),
    .S1(_0162_),
    .X(_0184_)
  );
  sky130_fd_sc_hd__mux2_2 _0471_ (
    .A0(_0183_),
    .A1(_0184_),
    .S(_0002_),
    .X(_0185_)
  );
  sky130_fd_sc_hd__mux2_2 _0472_ (
    .A0(_0182_),
    .A1(_0185_),
    .S(_0003_),
    .X(_0186_)
  );
  sky130_fd_sc_hd__buf_1 _0473_ (
    .A(_0186_),
    .X(data_out[3])
  );
  sky130_fd_sc_hd__mux4_2 _0474_ (
    .A0(\data_fifo[0][4] ),
    .A1(\data_fifo[1][4] ),
    .A2(\data_fifo[2][4] ),
    .A3(\data_fifo[3][4] ),
    .S0(_0152_),
    .S1(_0153_),
    .X(_0187_)
  );
  sky130_fd_sc_hd__mux4_2 _0475_ (
    .A0(\data_fifo[4][4] ),
    .A1(\data_fifo[5][4] ),
    .A2(\data_fifo[6][4] ),
    .A3(\data_fifo[7][4] ),
    .S0(_0158_),
    .S1(_0159_),
    .X(_0188_)
  );
  sky130_fd_sc_hd__mux2_2 _0476_ (
    .A0(_0187_),
    .A1(_0188_),
    .S(_0156_),
    .X(_0189_)
  );
  sky130_fd_sc_hd__mux4_2 _0477_ (
    .A0(\data_fifo[8][4] ),
    .A1(\data_fifo[9][4] ),
    .A2(\data_fifo[10][4] ),
    .A3(\data_fifo[11][4] ),
    .S0(_0161_),
    .S1(_0162_),
    .X(_0190_)
  );
  sky130_fd_sc_hd__mux4_2 _0478_ (
    .A0(\data_fifo[12][4] ),
    .A1(\data_fifo[13][4] ),
    .A2(\data_fifo[14][4] ),
    .A3(\data_fifo[15][4] ),
    .S0(_0161_),
    .S1(_0162_),
    .X(_0191_)
  );
  sky130_fd_sc_hd__mux2_2 _0479_ (
    .A0(_0190_),
    .A1(_0191_),
    .S(_0002_),
    .X(_0192_)
  );
  sky130_fd_sc_hd__mux2_2 _0480_ (
    .A0(_0189_),
    .A1(_0192_),
    .S(_0003_),
    .X(_0193_)
  );
  sky130_fd_sc_hd__buf_1 _0481_ (
    .A(_0193_),
    .X(data_out[4])
  );
  sky130_fd_sc_hd__mux4_2 _0482_ (
    .A0(\data_fifo[0][5] ),
    .A1(\data_fifo[1][5] ),
    .A2(\data_fifo[2][5] ),
    .A3(\data_fifo[3][5] ),
    .S0(_0152_),
    .S1(_0153_),
    .X(_0194_)
  );
  sky130_fd_sc_hd__mux4_2 _0483_ (
    .A0(\data_fifo[4][5] ),
    .A1(\data_fifo[5][5] ),
    .A2(\data_fifo[6][5] ),
    .A3(\data_fifo[7][5] ),
    .S0(_0158_),
    .S1(_0159_),
    .X(_0195_)
  );
  sky130_fd_sc_hd__mux2_2 _0484_ (
    .A0(_0194_),
    .A1(_0195_),
    .S(_0156_),
    .X(_0196_)
  );
  sky130_fd_sc_hd__mux4_2 _0485_ (
    .A0(\data_fifo[8][5] ),
    .A1(\data_fifo[9][5] ),
    .A2(\data_fifo[10][5] ),
    .A3(\data_fifo[11][5] ),
    .S0(_0161_),
    .S1(_0162_),
    .X(_0197_)
  );
  sky130_fd_sc_hd__mux4_2 _0486_ (
    .A0(\data_fifo[12][5] ),
    .A1(\data_fifo[13][5] ),
    .A2(\data_fifo[14][5] ),
    .A3(\data_fifo[15][5] ),
    .S0(_0161_),
    .S1(_0162_),
    .X(_0198_)
  );
  sky130_fd_sc_hd__mux2_2 _0487_ (
    .A0(_0197_),
    .A1(_0198_),
    .S(_0002_),
    .X(_0199_)
  );
  sky130_fd_sc_hd__mux2_2 _0488_ (
    .A0(_0196_),
    .A1(_0199_),
    .S(_0003_),
    .X(_0200_)
  );
  sky130_fd_sc_hd__buf_1 _0489_ (
    .A(_0200_),
    .X(data_out[5])
  );
  sky130_fd_sc_hd__mux4_2 _0490_ (
    .A0(\data_fifo[0][6] ),
    .A1(\data_fifo[1][6] ),
    .A2(\data_fifo[2][6] ),
    .A3(\data_fifo[3][6] ),
    .S0(_0152_),
    .S1(_0153_),
    .X(_0201_)
  );
  sky130_fd_sc_hd__mux4_2 _0491_ (
    .A0(\data_fifo[4][6] ),
    .A1(\data_fifo[5][6] ),
    .A2(\data_fifo[6][6] ),
    .A3(\data_fifo[7][6] ),
    .S0(_0158_),
    .S1(_0159_),
    .X(_0202_)
  );
  sky130_fd_sc_hd__mux2_2 _0492_ (
    .A0(_0201_),
    .A1(_0202_),
    .S(_0156_),
    .X(_0203_)
  );
  sky130_fd_sc_hd__mux4_2 _0493_ (
    .A0(\data_fifo[8][6] ),
    .A1(\data_fifo[9][6] ),
    .A2(\data_fifo[10][6] ),
    .A3(\data_fifo[11][6] ),
    .S0(_0161_),
    .S1(_0162_),
    .X(_0204_)
  );
  sky130_fd_sc_hd__mux4_2 _0494_ (
    .A0(\data_fifo[12][6] ),
    .A1(\data_fifo[13][6] ),
    .A2(\data_fifo[14][6] ),
    .A3(\data_fifo[15][6] ),
    .S0(_0000_),
    .S1(_0001_),
    .X(_0205_)
  );
  sky130_fd_sc_hd__mux2_2 _0495_ (
    .A0(_0204_),
    .A1(_0205_),
    .S(_0002_),
    .X(_0206_)
  );
  sky130_fd_sc_hd__mux2_2 _0496_ (
    .A0(_0203_),
    .A1(_0206_),
    .S(_0003_),
    .X(_0207_)
  );
  sky130_fd_sc_hd__buf_1 _0497_ (
    .A(_0207_),
    .X(data_out[6])
  );
  sky130_fd_sc_hd__mux4_2 _0498_ (
    .A0(\data_fifo[0][7] ),
    .A1(\data_fifo[1][7] ),
    .A2(\data_fifo[2][7] ),
    .A3(\data_fifo[3][7] ),
    .S0(_0152_),
    .S1(_0153_),
    .X(_0208_)
  );
  sky130_fd_sc_hd__mux4_2 _0499_ (
    .A0(\data_fifo[4][7] ),
    .A1(\data_fifo[5][7] ),
    .A2(\data_fifo[6][7] ),
    .A3(\data_fifo[7][7] ),
    .S0(_0158_),
    .S1(_0159_),
    .X(_0209_)
  );
  sky130_fd_sc_hd__mux2_2 _0500_ (
    .A0(_0208_),
    .A1(_0209_),
    .S(_0156_),
    .X(_0210_)
  );
  sky130_fd_sc_hd__mux4_2 _0501_ (
    .A0(\data_fifo[8][7] ),
    .A1(\data_fifo[9][7] ),
    .A2(\data_fifo[10][7] ),
    .A3(\data_fifo[11][7] ),
    .S0(_0161_),
    .S1(_0162_),
    .X(_0211_)
  );
  sky130_fd_sc_hd__mux4_2 _0502_ (
    .A0(\data_fifo[12][7] ),
    .A1(\data_fifo[13][7] ),
    .A2(\data_fifo[14][7] ),
    .A3(\data_fifo[15][7] ),
    .S0(_0000_),
    .S1(_0001_),
    .X(_0212_)
  );
  sky130_fd_sc_hd__mux2_2 _0503_ (
    .A0(_0211_),
    .A1(_0212_),
    .S(_0002_),
    .X(_0213_)
  );
  sky130_fd_sc_hd__mux2_2 _0504_ (
    .A0(_0210_),
    .A1(_0213_),
    .S(_0003_),
    .X(_0214_)
  );
  sky130_fd_sc_hd__buf_1 _0505_ (
    .A(_0214_),
    .X(data_out[7])
  );
  sky130_fd_sc_hd__buf_1 _0506_ (
    .A(data_in[0]),
    .X(_0215_)
  );
  sky130_fd_sc_hd__o21a_2 _0507_ (
    .A1(_0151_),
    .A2(pop),
    .B1(push),
    .X(_0216_)
  );
  sky130_fd_sc_hd__nand4b_2 _0508_ (
    .A_N(\ip_count[0] ),
    .B(rstn),
    .C(_0216_),
    .D(\ip_count[1] ),
    .Y(_0217_)
  );
  sky130_fd_sc_hd__buf_1 _0509_ (
    .A(\ip_count[3] ),
    .X(_0218_)
  );
  sky130_fd_sc_hd__buf_1 _0510_ (
    .A(\ip_count[2] ),
    .X(_0219_)
  );
  sky130_fd_sc_hd__nand2b_2 _0511_ (
    .A_N(_0218_),
    .B(_0219_),
    .Y(_0220_)
  );
  sky130_fd_sc_hd__nor2_2 _0512_ (
    .A(_0217_),
    .B(_0220_),
    .Y(_0221_)
  );
  sky130_fd_sc_hd__mux2_2 _0513_ (
    .A0(\data_fifo[6][0] ),
    .A1(_0215_),
    .S(_0221_),
    .X(_0222_)
  );
  sky130_fd_sc_hd__buf_1 _0514_ (
    .A(_0222_),
    .X(_0004_)
  );
  sky130_fd_sc_hd__buf_1 _0515_ (
    .A(data_in[1]),
    .X(_0223_)
  );
  sky130_fd_sc_hd__mux2_2 _0516_ (
    .A0(\data_fifo[6][1] ),
    .A1(_0223_),
    .S(_0221_),
    .X(_0224_)
  );
  sky130_fd_sc_hd__buf_1 _0517_ (
    .A(_0224_),
    .X(_0005_)
  );
  sky130_fd_sc_hd__buf_1 _0518_ (
    .A(data_in[2]),
    .X(_0225_)
  );
  sky130_fd_sc_hd__mux2_2 _0519_ (
    .A0(\data_fifo[6][2] ),
    .A1(_0225_),
    .S(_0221_),
    .X(_0226_)
  );
  sky130_fd_sc_hd__buf_1 _0520_ (
    .A(_0226_),
    .X(_0006_)
  );
  sky130_fd_sc_hd__buf_1 _0521_ (
    .A(data_in[3]),
    .X(_0227_)
  );
  sky130_fd_sc_hd__mux2_2 _0522_ (
    .A0(\data_fifo[6][3] ),
    .A1(_0227_),
    .S(_0221_),
    .X(_0228_)
  );
  sky130_fd_sc_hd__buf_1 _0523_ (
    .A(_0228_),
    .X(_0007_)
  );
  sky130_fd_sc_hd__buf_1 _0524_ (
    .A(data_in[4]),
    .X(_0229_)
  );
  sky130_fd_sc_hd__mux2_2 _0525_ (
    .A0(\data_fifo[6][4] ),
    .A1(_0229_),
    .S(_0221_),
    .X(_0230_)
  );
  sky130_fd_sc_hd__buf_1 _0526_ (
    .A(_0230_),
    .X(_0008_)
  );
  sky130_fd_sc_hd__buf_1 _0527_ (
    .A(data_in[5]),
    .X(_0231_)
  );
  sky130_fd_sc_hd__mux2_2 _0528_ (
    .A0(\data_fifo[6][5] ),
    .A1(_0231_),
    .S(_0221_),
    .X(_0232_)
  );
  sky130_fd_sc_hd__buf_1 _0529_ (
    .A(_0232_),
    .X(_0009_)
  );
  sky130_fd_sc_hd__buf_1 _0530_ (
    .A(data_in[6]),
    .X(_0233_)
  );
  sky130_fd_sc_hd__mux2_2 _0531_ (
    .A0(\data_fifo[6][6] ),
    .A1(_0233_),
    .S(_0221_),
    .X(_0234_)
  );
  sky130_fd_sc_hd__buf_1 _0532_ (
    .A(_0234_),
    .X(_0010_)
  );
  sky130_fd_sc_hd__buf_1 _0533_ (
    .A(data_in[7]),
    .X(_0235_)
  );
  sky130_fd_sc_hd__mux2_2 _0534_ (
    .A0(\data_fifo[6][7] ),
    .A1(_0235_),
    .S(_0221_),
    .X(_0236_)
  );
  sky130_fd_sc_hd__buf_1 _0535_ (
    .A(_0236_),
    .X(_0011_)
  );
  sky130_fd_sc_hd__and2_2 _0536_ (
    .A(\ip_count[0] ),
    .B(_0216_),
    .X(_0237_)
  );
  sky130_fd_sc_hd__and3b_2 _0537_ (
    .A_N(\ip_count[1] ),
    .B(rstn),
    .C(_0237_),
    .X(_0238_)
  );
  sky130_fd_sc_hd__nor3b_2 _0538_ (
    .A(_0218_),
    .B(_0219_),
    .C_N(_0238_),
    .Y(_0239_)
  );
  sky130_fd_sc_hd__mux2_2 _0539_ (
    .A0(\data_fifo[1][0] ),
    .A1(_0215_),
    .S(_0239_),
    .X(_0240_)
  );
  sky130_fd_sc_hd__buf_1 _0540_ (
    .A(_0240_),
    .X(_0012_)
  );
  sky130_fd_sc_hd__mux2_2 _0541_ (
    .A0(\data_fifo[1][1] ),
    .A1(_0223_),
    .S(_0239_),
    .X(_0241_)
  );
  sky130_fd_sc_hd__buf_1 _0542_ (
    .A(_0241_),
    .X(_0013_)
  );
  sky130_fd_sc_hd__mux2_2 _0543_ (
    .A0(\data_fifo[1][2] ),
    .A1(_0225_),
    .S(_0239_),
    .X(_0242_)
  );
  sky130_fd_sc_hd__buf_1 _0544_ (
    .A(_0242_),
    .X(_0014_)
  );
  sky130_fd_sc_hd__mux2_2 _0545_ (
    .A0(\data_fifo[1][3] ),
    .A1(_0227_),
    .S(_0239_),
    .X(_0243_)
  );
  sky130_fd_sc_hd__buf_1 _0546_ (
    .A(_0243_),
    .X(_0015_)
  );
  sky130_fd_sc_hd__mux2_2 _0547_ (
    .A0(\data_fifo[1][4] ),
    .A1(_0229_),
    .S(_0239_),
    .X(_0244_)
  );
  sky130_fd_sc_hd__buf_1 _0548_ (
    .A(_0244_),
    .X(_0016_)
  );
  sky130_fd_sc_hd__mux2_2 _0549_ (
    .A0(\data_fifo[1][5] ),
    .A1(_0231_),
    .S(_0239_),
    .X(_0245_)
  );
  sky130_fd_sc_hd__buf_1 _0550_ (
    .A(_0245_),
    .X(_0017_)
  );
  sky130_fd_sc_hd__mux2_2 _0551_ (
    .A0(\data_fifo[1][6] ),
    .A1(_0233_),
    .S(_0239_),
    .X(_0246_)
  );
  sky130_fd_sc_hd__buf_1 _0552_ (
    .A(_0246_),
    .X(_0018_)
  );
  sky130_fd_sc_hd__mux2_2 _0553_ (
    .A0(\data_fifo[1][7] ),
    .A1(_0235_),
    .S(_0239_),
    .X(_0247_)
  );
  sky130_fd_sc_hd__buf_1 _0554_ (
    .A(_0247_),
    .X(_0019_)
  );
  sky130_fd_sc_hd__and3_2 _0555_ (
    .A(\ip_count[1] ),
    .B(rstn),
    .C(_0237_),
    .X(_0248_)
  );
  sky130_fd_sc_hd__nand3_2 _0556_ (
    .A(_0218_),
    .B(_0219_),
    .C(_0248_),
    .Y(_0249_)
  );
  sky130_fd_sc_hd__mux2_2 _0557_ (
    .A0(_0215_),
    .A1(\data_fifo[15][0] ),
    .S(_0249_),
    .X(_0250_)
  );
  sky130_fd_sc_hd__buf_1 _0558_ (
    .A(_0250_),
    .X(_0020_)
  );
  sky130_fd_sc_hd__mux2_2 _0559_ (
    .A0(_0223_),
    .A1(\data_fifo[15][1] ),
    .S(_0249_),
    .X(_0251_)
  );
  sky130_fd_sc_hd__buf_1 _0560_ (
    .A(_0251_),
    .X(_0021_)
  );
  sky130_fd_sc_hd__mux2_2 _0561_ (
    .A0(_0225_),
    .A1(\data_fifo[15][2] ),
    .S(_0249_),
    .X(_0252_)
  );
  sky130_fd_sc_hd__buf_1 _0562_ (
    .A(_0252_),
    .X(_0022_)
  );
  sky130_fd_sc_hd__mux2_2 _0563_ (
    .A0(_0227_),
    .A1(\data_fifo[15][3] ),
    .S(_0249_),
    .X(_0253_)
  );
  sky130_fd_sc_hd__buf_1 _0564_ (
    .A(_0253_),
    .X(_0023_)
  );
  sky130_fd_sc_hd__mux2_2 _0565_ (
    .A0(_0229_),
    .A1(\data_fifo[15][4] ),
    .S(_0249_),
    .X(_0254_)
  );
  sky130_fd_sc_hd__buf_1 _0566_ (
    .A(_0254_),
    .X(_0024_)
  );
  sky130_fd_sc_hd__mux2_2 _0567_ (
    .A0(_0231_),
    .A1(\data_fifo[15][5] ),
    .S(_0249_),
    .X(_0255_)
  );
  sky130_fd_sc_hd__buf_1 _0568_ (
    .A(_0255_),
    .X(_0025_)
  );
  sky130_fd_sc_hd__mux2_2 _0569_ (
    .A0(_0233_),
    .A1(\data_fifo[15][6] ),
    .S(_0249_),
    .X(_0256_)
  );
  sky130_fd_sc_hd__buf_1 _0570_ (
    .A(_0256_),
    .X(_0026_)
  );
  sky130_fd_sc_hd__mux2_2 _0571_ (
    .A0(_0235_),
    .A1(\data_fifo[15][7] ),
    .S(_0249_),
    .X(_0257_)
  );
  sky130_fd_sc_hd__buf_1 _0572_ (
    .A(_0257_),
    .X(_0027_)
  );
  sky130_fd_sc_hd__nand2_2 _0573_ (
    .A(\ip_count[3] ),
    .B(\ip_count[2] ),
    .Y(_0258_)
  );
  sky130_fd_sc_hd__or4bb_2 _0574_ (
    .A(\ip_count[1] ),
    .B(\ip_count[0] ),
    .C_N(rstn),
    .D_N(_0216_),
    .X(_0259_)
  );
  sky130_fd_sc_hd__or2_2 _0575_ (
    .A(_0258_),
    .B(_0259_),
    .X(_0260_)
  );
  sky130_fd_sc_hd__buf_1 _0576_ (
    .A(_0260_),
    .X(_0261_)
  );
  sky130_fd_sc_hd__mux2_2 _0577_ (
    .A0(_0215_),
    .A1(\data_fifo[12][0] ),
    .S(_0261_),
    .X(_0262_)
  );
  sky130_fd_sc_hd__buf_1 _0578_ (
    .A(_0262_),
    .X(_0028_)
  );
  sky130_fd_sc_hd__mux2_2 _0579_ (
    .A0(_0223_),
    .A1(\data_fifo[12][1] ),
    .S(_0261_),
    .X(_0263_)
  );
  sky130_fd_sc_hd__buf_1 _0580_ (
    .A(_0263_),
    .X(_0029_)
  );
  sky130_fd_sc_hd__mux2_2 _0581_ (
    .A0(_0225_),
    .A1(\data_fifo[12][2] ),
    .S(_0261_),
    .X(_0264_)
  );
  sky130_fd_sc_hd__buf_1 _0582_ (
    .A(_0264_),
    .X(_0030_)
  );
  sky130_fd_sc_hd__mux2_2 _0583_ (
    .A0(_0227_),
    .A1(\data_fifo[12][3] ),
    .S(_0261_),
    .X(_0265_)
  );
  sky130_fd_sc_hd__buf_1 _0584_ (
    .A(_0265_),
    .X(_0031_)
  );
  sky130_fd_sc_hd__mux2_2 _0585_ (
    .A0(_0229_),
    .A1(\data_fifo[12][4] ),
    .S(_0261_),
    .X(_0266_)
  );
  sky130_fd_sc_hd__buf_1 _0586_ (
    .A(_0266_),
    .X(_0032_)
  );
  sky130_fd_sc_hd__mux2_2 _0587_ (
    .A0(_0231_),
    .A1(\data_fifo[12][5] ),
    .S(_0261_),
    .X(_0267_)
  );
  sky130_fd_sc_hd__buf_1 _0588_ (
    .A(_0267_),
    .X(_0033_)
  );
  sky130_fd_sc_hd__mux2_2 _0589_ (
    .A0(_0233_),
    .A1(\data_fifo[12][6] ),
    .S(_0261_),
    .X(_0268_)
  );
  sky130_fd_sc_hd__buf_1 _0590_ (
    .A(_0268_),
    .X(_0034_)
  );
  sky130_fd_sc_hd__mux2_2 _0591_ (
    .A0(_0235_),
    .A1(\data_fifo[12][7] ),
    .S(_0261_),
    .X(_0269_)
  );
  sky130_fd_sc_hd__buf_1 _0592_ (
    .A(_0269_),
    .X(_0035_)
  );
  sky130_fd_sc_hd__and3_2 _0593_ (
    .A(_0218_),
    .B(_0219_),
    .C(_0238_),
    .X(_0270_)
  );
  sky130_fd_sc_hd__buf_1 _0594_ (
    .A(_0270_),
    .X(_0271_)
  );
  sky130_fd_sc_hd__mux2_2 _0595_ (
    .A0(\data_fifo[13][0] ),
    .A1(_0215_),
    .S(_0271_),
    .X(_0272_)
  );
  sky130_fd_sc_hd__buf_1 _0596_ (
    .A(_0272_),
    .X(_0036_)
  );
  sky130_fd_sc_hd__mux2_2 _0597_ (
    .A0(\data_fifo[13][1] ),
    .A1(_0223_),
    .S(_0271_),
    .X(_0273_)
  );
  sky130_fd_sc_hd__buf_1 _0598_ (
    .A(_0273_),
    .X(_0037_)
  );
  sky130_fd_sc_hd__mux2_2 _0599_ (
    .A0(\data_fifo[13][2] ),
    .A1(_0225_),
    .S(_0271_),
    .X(_0274_)
  );
  sky130_fd_sc_hd__buf_1 _0600_ (
    .A(_0274_),
    .X(_0038_)
  );
  sky130_fd_sc_hd__mux2_2 _0601_ (
    .A0(\data_fifo[13][3] ),
    .A1(_0227_),
    .S(_0271_),
    .X(_0275_)
  );
  sky130_fd_sc_hd__buf_1 _0602_ (
    .A(_0275_),
    .X(_0039_)
  );
  sky130_fd_sc_hd__mux2_2 _0603_ (
    .A0(\data_fifo[13][4] ),
    .A1(_0229_),
    .S(_0271_),
    .X(_0276_)
  );
  sky130_fd_sc_hd__buf_1 _0604_ (
    .A(_0276_),
    .X(_0040_)
  );
  sky130_fd_sc_hd__mux2_2 _0605_ (
    .A0(\data_fifo[13][5] ),
    .A1(_0231_),
    .S(_0271_),
    .X(_0277_)
  );
  sky130_fd_sc_hd__buf_1 _0606_ (
    .A(_0277_),
    .X(_0041_)
  );
  sky130_fd_sc_hd__mux2_2 _0607_ (
    .A0(\data_fifo[13][6] ),
    .A1(_0233_),
    .S(_0271_),
    .X(_0278_)
  );
  sky130_fd_sc_hd__buf_1 _0608_ (
    .A(_0278_),
    .X(_0042_)
  );
  sky130_fd_sc_hd__mux2_2 _0609_ (
    .A0(\data_fifo[13][7] ),
    .A1(_0235_),
    .S(_0271_),
    .X(_0279_)
  );
  sky130_fd_sc_hd__buf_1 _0610_ (
    .A(_0279_),
    .X(_0043_)
  );
  sky130_fd_sc_hd__or2_2 _0611_ (
    .A(_0218_),
    .B(_0219_),
    .X(_0280_)
  );
  sky130_fd_sc_hd__nor2_2 _0612_ (
    .A(_0217_),
    .B(_0280_),
    .Y(_0281_)
  );
  sky130_fd_sc_hd__mux2_2 _0613_ (
    .A0(\data_fifo[2][0] ),
    .A1(_0215_),
    .S(_0281_),
    .X(_0282_)
  );
  sky130_fd_sc_hd__buf_1 _0614_ (
    .A(_0282_),
    .X(_0044_)
  );
  sky130_fd_sc_hd__mux2_2 _0615_ (
    .A0(\data_fifo[2][1] ),
    .A1(_0223_),
    .S(_0281_),
    .X(_0283_)
  );
  sky130_fd_sc_hd__buf_1 _0616_ (
    .A(_0283_),
    .X(_0045_)
  );
  sky130_fd_sc_hd__mux2_2 _0617_ (
    .A0(\data_fifo[2][2] ),
    .A1(_0225_),
    .S(_0281_),
    .X(_0284_)
  );
  sky130_fd_sc_hd__buf_1 _0618_ (
    .A(_0284_),
    .X(_0046_)
  );
  sky130_fd_sc_hd__mux2_2 _0619_ (
    .A0(\data_fifo[2][3] ),
    .A1(_0227_),
    .S(_0281_),
    .X(_0285_)
  );
  sky130_fd_sc_hd__buf_1 _0620_ (
    .A(_0285_),
    .X(_0047_)
  );
  sky130_fd_sc_hd__mux2_2 _0621_ (
    .A0(\data_fifo[2][4] ),
    .A1(_0229_),
    .S(_0281_),
    .X(_0286_)
  );
  sky130_fd_sc_hd__buf_1 _0622_ (
    .A(_0286_),
    .X(_0048_)
  );
  sky130_fd_sc_hd__mux2_2 _0623_ (
    .A0(\data_fifo[2][5] ),
    .A1(_0231_),
    .S(_0281_),
    .X(_0287_)
  );
  sky130_fd_sc_hd__buf_1 _0624_ (
    .A(_0287_),
    .X(_0049_)
  );
  sky130_fd_sc_hd__mux2_2 _0625_ (
    .A0(\data_fifo[2][6] ),
    .A1(_0233_),
    .S(_0281_),
    .X(_0288_)
  );
  sky130_fd_sc_hd__buf_1 _0626_ (
    .A(_0288_),
    .X(_0050_)
  );
  sky130_fd_sc_hd__mux2_2 _0627_ (
    .A0(\data_fifo[2][7] ),
    .A1(_0235_),
    .S(_0281_),
    .X(_0289_)
  );
  sky130_fd_sc_hd__buf_1 _0628_ (
    .A(_0289_),
    .X(_0051_)
  );
  sky130_fd_sc_hd__or2b_2 _0629_ (
    .A(_0219_),
    .B_N(_0218_),
    .X(_0290_)
  );
  sky130_fd_sc_hd__nor2_2 _0630_ (
    .A(_0217_),
    .B(_0290_),
    .Y(_0291_)
  );
  sky130_fd_sc_hd__mux2_2 _0631_ (
    .A0(\data_fifo[10][0] ),
    .A1(_0215_),
    .S(_0291_),
    .X(_0292_)
  );
  sky130_fd_sc_hd__buf_1 _0632_ (
    .A(_0292_),
    .X(_0052_)
  );
  sky130_fd_sc_hd__mux2_2 _0633_ (
    .A0(\data_fifo[10][1] ),
    .A1(_0223_),
    .S(_0291_),
    .X(_0293_)
  );
  sky130_fd_sc_hd__buf_1 _0634_ (
    .A(_0293_),
    .X(_0053_)
  );
  sky130_fd_sc_hd__mux2_2 _0635_ (
    .A0(\data_fifo[10][2] ),
    .A1(_0225_),
    .S(_0291_),
    .X(_0294_)
  );
  sky130_fd_sc_hd__buf_1 _0636_ (
    .A(_0294_),
    .X(_0054_)
  );
  sky130_fd_sc_hd__mux2_2 _0637_ (
    .A0(\data_fifo[10][3] ),
    .A1(_0227_),
    .S(_0291_),
    .X(_0295_)
  );
  sky130_fd_sc_hd__buf_1 _0638_ (
    .A(_0295_),
    .X(_0055_)
  );
  sky130_fd_sc_hd__mux2_2 _0639_ (
    .A0(\data_fifo[10][4] ),
    .A1(_0229_),
    .S(_0291_),
    .X(_0296_)
  );
  sky130_fd_sc_hd__buf_1 _0640_ (
    .A(_0296_),
    .X(_0056_)
  );
  sky130_fd_sc_hd__mux2_2 _0641_ (
    .A0(\data_fifo[10][5] ),
    .A1(_0231_),
    .S(_0291_),
    .X(_0297_)
  );
  sky130_fd_sc_hd__buf_1 _0642_ (
    .A(_0297_),
    .X(_0057_)
  );
  sky130_fd_sc_hd__mux2_2 _0643_ (
    .A0(\data_fifo[10][6] ),
    .A1(_0233_),
    .S(_0291_),
    .X(_0298_)
  );
  sky130_fd_sc_hd__buf_1 _0644_ (
    .A(_0298_),
    .X(_0058_)
  );
  sky130_fd_sc_hd__mux2_2 _0645_ (
    .A0(\data_fifo[10][7] ),
    .A1(_0235_),
    .S(_0291_),
    .X(_0299_)
  );
  sky130_fd_sc_hd__buf_1 _0646_ (
    .A(_0299_),
    .X(_0059_)
  );
  sky130_fd_sc_hd__nand3b_2 _0647_ (
    .A_N(_0219_),
    .B(_0248_),
    .C(_0218_),
    .Y(_0300_)
  );
  sky130_fd_sc_hd__mux2_2 _0648_ (
    .A0(_0215_),
    .A1(\data_fifo[11][0] ),
    .S(_0300_),
    .X(_0301_)
  );
  sky130_fd_sc_hd__buf_1 _0649_ (
    .A(_0301_),
    .X(_0060_)
  );
  sky130_fd_sc_hd__mux2_2 _0650_ (
    .A0(_0223_),
    .A1(\data_fifo[11][1] ),
    .S(_0300_),
    .X(_0302_)
  );
  sky130_fd_sc_hd__buf_1 _0651_ (
    .A(_0302_),
    .X(_0061_)
  );
  sky130_fd_sc_hd__mux2_2 _0652_ (
    .A0(_0225_),
    .A1(\data_fifo[11][2] ),
    .S(_0300_),
    .X(_0303_)
  );
  sky130_fd_sc_hd__buf_1 _0653_ (
    .A(_0303_),
    .X(_0062_)
  );
  sky130_fd_sc_hd__mux2_2 _0654_ (
    .A0(_0227_),
    .A1(\data_fifo[11][3] ),
    .S(_0300_),
    .X(_0304_)
  );
  sky130_fd_sc_hd__buf_1 _0655_ (
    .A(_0304_),
    .X(_0063_)
  );
  sky130_fd_sc_hd__mux2_2 _0656_ (
    .A0(_0229_),
    .A1(\data_fifo[11][4] ),
    .S(_0300_),
    .X(_0305_)
  );
  sky130_fd_sc_hd__buf_1 _0657_ (
    .A(_0305_),
    .X(_0064_)
  );
  sky130_fd_sc_hd__mux2_2 _0658_ (
    .A0(_0231_),
    .A1(\data_fifo[11][5] ),
    .S(_0300_),
    .X(_0306_)
  );
  sky130_fd_sc_hd__buf_1 _0659_ (
    .A(_0306_),
    .X(_0065_)
  );
  sky130_fd_sc_hd__mux2_2 _0660_ (
    .A0(_0233_),
    .A1(\data_fifo[11][6] ),
    .S(_0300_),
    .X(_0307_)
  );
  sky130_fd_sc_hd__buf_1 _0661_ (
    .A(_0307_),
    .X(_0066_)
  );
  sky130_fd_sc_hd__mux2_2 _0662_ (
    .A0(_0235_),
    .A1(\data_fifo[11][7] ),
    .S(_0300_),
    .X(_0308_)
  );
  sky130_fd_sc_hd__buf_1 _0663_ (
    .A(_0308_),
    .X(_0067_)
  );
  sky130_fd_sc_hd__nor2_2 _0664_ (
    .A(_0280_),
    .B(_0259_),
    .Y(_0309_)
  );
  sky130_fd_sc_hd__mux2_2 _0665_ (
    .A0(\data_fifo[0][0] ),
    .A1(data_in[0]),
    .S(_0309_),
    .X(_0310_)
  );
  sky130_fd_sc_hd__buf_1 _0666_ (
    .A(_0310_),
    .X(_0068_)
  );
  sky130_fd_sc_hd__mux2_2 _0667_ (
    .A0(\data_fifo[0][1] ),
    .A1(data_in[1]),
    .S(_0309_),
    .X(_0311_)
  );
  sky130_fd_sc_hd__buf_1 _0668_ (
    .A(_0311_),
    .X(_0069_)
  );
  sky130_fd_sc_hd__mux2_2 _0669_ (
    .A0(\data_fifo[0][2] ),
    .A1(data_in[2]),
    .S(_0309_),
    .X(_0312_)
  );
  sky130_fd_sc_hd__buf_1 _0670_ (
    .A(_0312_),
    .X(_0070_)
  );
  sky130_fd_sc_hd__mux2_2 _0671_ (
    .A0(\data_fifo[0][3] ),
    .A1(data_in[3]),
    .S(_0309_),
    .X(_0313_)
  );
  sky130_fd_sc_hd__buf_1 _0672_ (
    .A(_0313_),
    .X(_0071_)
  );
  sky130_fd_sc_hd__mux2_2 _0673_ (
    .A0(\data_fifo[0][4] ),
    .A1(data_in[4]),
    .S(_0309_),
    .X(_0314_)
  );
  sky130_fd_sc_hd__buf_1 _0674_ (
    .A(_0314_),
    .X(_0072_)
  );
  sky130_fd_sc_hd__mux2_2 _0675_ (
    .A0(\data_fifo[0][5] ),
    .A1(data_in[5]),
    .S(_0309_),
    .X(_0315_)
  );
  sky130_fd_sc_hd__buf_1 _0676_ (
    .A(_0315_),
    .X(_0073_)
  );
  sky130_fd_sc_hd__mux2_2 _0677_ (
    .A0(\data_fifo[0][6] ),
    .A1(data_in[6]),
    .S(_0309_),
    .X(_0316_)
  );
  sky130_fd_sc_hd__buf_1 _0678_ (
    .A(_0316_),
    .X(_0074_)
  );
  sky130_fd_sc_hd__mux2_2 _0679_ (
    .A0(\data_fifo[0][7] ),
    .A1(data_in[7]),
    .S(_0309_),
    .X(_0317_)
  );
  sky130_fd_sc_hd__buf_1 _0680_ (
    .A(_0317_),
    .X(_0075_)
  );
  sky130_fd_sc_hd__nand2b_2 _0681_ (
    .A_N(_0280_),
    .B(_0248_),
    .Y(_0318_)
  );
  sky130_fd_sc_hd__mux2_2 _0682_ (
    .A0(_0215_),
    .A1(\data_fifo[3][0] ),
    .S(_0318_),
    .X(_0319_)
  );
  sky130_fd_sc_hd__buf_1 _0683_ (
    .A(_0319_),
    .X(_0076_)
  );
  sky130_fd_sc_hd__mux2_2 _0684_ (
    .A0(_0223_),
    .A1(\data_fifo[3][1] ),
    .S(_0318_),
    .X(_0320_)
  );
  sky130_fd_sc_hd__buf_1 _0685_ (
    .A(_0320_),
    .X(_0077_)
  );
  sky130_fd_sc_hd__mux2_2 _0686_ (
    .A0(_0225_),
    .A1(\data_fifo[3][2] ),
    .S(_0318_),
    .X(_0321_)
  );
  sky130_fd_sc_hd__buf_1 _0687_ (
    .A(_0321_),
    .X(_0078_)
  );
  sky130_fd_sc_hd__mux2_2 _0688_ (
    .A0(_0227_),
    .A1(\data_fifo[3][3] ),
    .S(_0318_),
    .X(_0322_)
  );
  sky130_fd_sc_hd__buf_1 _0689_ (
    .A(_0322_),
    .X(_0079_)
  );
  sky130_fd_sc_hd__mux2_2 _0690_ (
    .A0(_0229_),
    .A1(\data_fifo[3][4] ),
    .S(_0318_),
    .X(_0323_)
  );
  sky130_fd_sc_hd__buf_1 _0691_ (
    .A(_0323_),
    .X(_0080_)
  );
  sky130_fd_sc_hd__mux2_2 _0692_ (
    .A0(_0231_),
    .A1(\data_fifo[3][5] ),
    .S(_0318_),
    .X(_0324_)
  );
  sky130_fd_sc_hd__buf_1 _0693_ (
    .A(_0324_),
    .X(_0081_)
  );
  sky130_fd_sc_hd__mux2_2 _0694_ (
    .A0(_0233_),
    .A1(\data_fifo[3][6] ),
    .S(_0318_),
    .X(_0325_)
  );
  sky130_fd_sc_hd__buf_1 _0695_ (
    .A(_0325_),
    .X(_0082_)
  );
  sky130_fd_sc_hd__mux2_2 _0696_ (
    .A0(_0235_),
    .A1(\data_fifo[3][7] ),
    .S(_0318_),
    .X(_0326_)
  );
  sky130_fd_sc_hd__buf_1 _0697_ (
    .A(_0326_),
    .X(_0083_)
  );
  sky130_fd_sc_hd__nor2_2 _0698_ (
    .A(_0259_),
    .B(_0290_),
    .Y(_0327_)
  );
  sky130_fd_sc_hd__mux2_2 _0699_ (
    .A0(\data_fifo[8][0] ),
    .A1(data_in[0]),
    .S(_0327_),
    .X(_0328_)
  );
  sky130_fd_sc_hd__buf_1 _0700_ (
    .A(_0328_),
    .X(_0084_)
  );
  sky130_fd_sc_hd__mux2_2 _0701_ (
    .A0(\data_fifo[8][1] ),
    .A1(data_in[1]),
    .S(_0327_),
    .X(_0329_)
  );
  sky130_fd_sc_hd__buf_1 _0702_ (
    .A(_0329_),
    .X(_0085_)
  );
  sky130_fd_sc_hd__mux2_2 _0703_ (
    .A0(\data_fifo[8][2] ),
    .A1(data_in[2]),
    .S(_0327_),
    .X(_0330_)
  );
  sky130_fd_sc_hd__buf_1 _0704_ (
    .A(_0330_),
    .X(_0086_)
  );
  sky130_fd_sc_hd__mux2_2 _0705_ (
    .A0(\data_fifo[8][3] ),
    .A1(data_in[3]),
    .S(_0327_),
    .X(_0331_)
  );
  sky130_fd_sc_hd__buf_1 _0706_ (
    .A(_0331_),
    .X(_0087_)
  );
  sky130_fd_sc_hd__mux2_2 _0707_ (
    .A0(\data_fifo[8][4] ),
    .A1(data_in[4]),
    .S(_0327_),
    .X(_0332_)
  );
  sky130_fd_sc_hd__buf_1 _0708_ (
    .A(_0332_),
    .X(_0088_)
  );
  sky130_fd_sc_hd__mux2_2 _0709_ (
    .A0(\data_fifo[8][5] ),
    .A1(data_in[5]),
    .S(_0327_),
    .X(_0333_)
  );
  sky130_fd_sc_hd__buf_1 _0710_ (
    .A(_0333_),
    .X(_0089_)
  );
  sky130_fd_sc_hd__mux2_2 _0711_ (
    .A0(\data_fifo[8][6] ),
    .A1(data_in[6]),
    .S(_0327_),
    .X(_0334_)
  );
  sky130_fd_sc_hd__buf_1 _0712_ (
    .A(_0334_),
    .X(_0090_)
  );
  sky130_fd_sc_hd__mux2_2 _0713_ (
    .A0(\data_fifo[8][7] ),
    .A1(data_in[7]),
    .S(_0327_),
    .X(_0335_)
  );
  sky130_fd_sc_hd__buf_1 _0714_ (
    .A(_0335_),
    .X(_0091_)
  );
  sky130_fd_sc_hd__nand2b_2 _0715_ (
    .A_N(_0220_),
    .B(_0248_),
    .Y(_0336_)
  );
  sky130_fd_sc_hd__mux2_2 _0716_ (
    .A0(_0215_),
    .A1(\data_fifo[7][0] ),
    .S(_0336_),
    .X(_0337_)
  );
  sky130_fd_sc_hd__buf_1 _0717_ (
    .A(_0337_),
    .X(_0092_)
  );
  sky130_fd_sc_hd__mux2_2 _0718_ (
    .A0(_0223_),
    .A1(\data_fifo[7][1] ),
    .S(_0336_),
    .X(_0338_)
  );
  sky130_fd_sc_hd__buf_1 _0719_ (
    .A(_0338_),
    .X(_0093_)
  );
  sky130_fd_sc_hd__mux2_2 _0720_ (
    .A0(_0225_),
    .A1(\data_fifo[7][2] ),
    .S(_0336_),
    .X(_0339_)
  );
  sky130_fd_sc_hd__buf_1 _0721_ (
    .A(_0339_),
    .X(_0094_)
  );
  sky130_fd_sc_hd__mux2_2 _0722_ (
    .A0(_0227_),
    .A1(\data_fifo[7][3] ),
    .S(_0336_),
    .X(_0340_)
  );
  sky130_fd_sc_hd__buf_1 _0723_ (
    .A(_0340_),
    .X(_0095_)
  );
  sky130_fd_sc_hd__mux2_2 _0724_ (
    .A0(_0229_),
    .A1(\data_fifo[7][4] ),
    .S(_0336_),
    .X(_0341_)
  );
  sky130_fd_sc_hd__buf_1 _0725_ (
    .A(_0341_),
    .X(_0096_)
  );
  sky130_fd_sc_hd__mux2_2 _0726_ (
    .A0(_0231_),
    .A1(\data_fifo[7][5] ),
    .S(_0336_),
    .X(_0342_)
  );
  sky130_fd_sc_hd__buf_1 _0727_ (
    .A(_0342_),
    .X(_0097_)
  );
  sky130_fd_sc_hd__mux2_2 _0728_ (
    .A0(_0233_),
    .A1(\data_fifo[7][6] ),
    .S(_0336_),
    .X(_0343_)
  );
  sky130_fd_sc_hd__buf_1 _0729_ (
    .A(_0343_),
    .X(_0098_)
  );
  sky130_fd_sc_hd__mux2_2 _0730_ (
    .A0(_0235_),
    .A1(\data_fifo[7][7] ),
    .S(_0336_),
    .X(_0344_)
  );
  sky130_fd_sc_hd__buf_1 _0731_ (
    .A(_0344_),
    .X(_0099_)
  );
  sky130_fd_sc_hd__nor2_2 _0732_ (
    .A(_0220_),
    .B(_0259_),
    .Y(_0345_)
  );
  sky130_fd_sc_hd__mux2_2 _0733_ (
    .A0(\data_fifo[4][0] ),
    .A1(data_in[0]),
    .S(_0345_),
    .X(_0346_)
  );
  sky130_fd_sc_hd__buf_1 _0734_ (
    .A(_0346_),
    .X(_0100_)
  );
  sky130_fd_sc_hd__mux2_2 _0735_ (
    .A0(\data_fifo[4][1] ),
    .A1(data_in[1]),
    .S(_0345_),
    .X(_0347_)
  );
  sky130_fd_sc_hd__buf_1 _0736_ (
    .A(_0347_),
    .X(_0101_)
  );
  sky130_fd_sc_hd__mux2_2 _0737_ (
    .A0(\data_fifo[4][2] ),
    .A1(data_in[2]),
    .S(_0345_),
    .X(_0348_)
  );
  sky130_fd_sc_hd__buf_1 _0738_ (
    .A(_0348_),
    .X(_0102_)
  );
  sky130_fd_sc_hd__mux2_2 _0739_ (
    .A0(\data_fifo[4][3] ),
    .A1(data_in[3]),
    .S(_0345_),
    .X(_0349_)
  );
  sky130_fd_sc_hd__buf_1 _0740_ (
    .A(_0349_),
    .X(_0103_)
  );
  sky130_fd_sc_hd__mux2_2 _0741_ (
    .A0(\data_fifo[4][4] ),
    .A1(data_in[4]),
    .S(_0345_),
    .X(_0350_)
  );
  sky130_fd_sc_hd__buf_1 _0742_ (
    .A(_0350_),
    .X(_0104_)
  );
  sky130_fd_sc_hd__mux2_2 _0743_ (
    .A0(\data_fifo[4][5] ),
    .A1(data_in[5]),
    .S(_0345_),
    .X(_0351_)
  );
  sky130_fd_sc_hd__buf_1 _0744_ (
    .A(_0351_),
    .X(_0105_)
  );
  sky130_fd_sc_hd__mux2_2 _0745_ (
    .A0(\data_fifo[4][6] ),
    .A1(data_in[6]),
    .S(_0345_),
    .X(_0352_)
  );
  sky130_fd_sc_hd__buf_1 _0746_ (
    .A(_0352_),
    .X(_0106_)
  );
  sky130_fd_sc_hd__mux2_2 _0747_ (
    .A0(\data_fifo[4][7] ),
    .A1(data_in[7]),
    .S(_0345_),
    .X(_0353_)
  );
  sky130_fd_sc_hd__buf_1 _0748_ (
    .A(_0353_),
    .X(_0107_)
  );
  sky130_fd_sc_hd__and3b_2 _0749_ (
    .A_N(_0219_),
    .B(_0238_),
    .C(_0218_),
    .X(_0354_)
  );
  sky130_fd_sc_hd__buf_1 _0750_ (
    .A(_0354_),
    .X(_0355_)
  );
  sky130_fd_sc_hd__mux2_2 _0751_ (
    .A0(\data_fifo[9][0] ),
    .A1(data_in[0]),
    .S(_0355_),
    .X(_0356_)
  );
  sky130_fd_sc_hd__buf_1 _0752_ (
    .A(_0356_),
    .X(_0108_)
  );
  sky130_fd_sc_hd__mux2_2 _0753_ (
    .A0(\data_fifo[9][1] ),
    .A1(data_in[1]),
    .S(_0355_),
    .X(_0357_)
  );
  sky130_fd_sc_hd__buf_1 _0754_ (
    .A(_0357_),
    .X(_0109_)
  );
  sky130_fd_sc_hd__mux2_2 _0755_ (
    .A0(\data_fifo[9][2] ),
    .A1(data_in[2]),
    .S(_0355_),
    .X(_0358_)
  );
  sky130_fd_sc_hd__buf_1 _0756_ (
    .A(_0358_),
    .X(_0110_)
  );
  sky130_fd_sc_hd__mux2_2 _0757_ (
    .A0(\data_fifo[9][3] ),
    .A1(data_in[3]),
    .S(_0355_),
    .X(_0359_)
  );
  sky130_fd_sc_hd__buf_1 _0758_ (
    .A(_0359_),
    .X(_0111_)
  );
  sky130_fd_sc_hd__mux2_2 _0759_ (
    .A0(\data_fifo[9][4] ),
    .A1(data_in[4]),
    .S(_0355_),
    .X(_0360_)
  );
  sky130_fd_sc_hd__buf_1 _0760_ (
    .A(_0360_),
    .X(_0112_)
  );
  sky130_fd_sc_hd__mux2_2 _0761_ (
    .A0(\data_fifo[9][5] ),
    .A1(data_in[5]),
    .S(_0355_),
    .X(_0361_)
  );
  sky130_fd_sc_hd__buf_1 _0762_ (
    .A(_0361_),
    .X(_0113_)
  );
  sky130_fd_sc_hd__mux2_2 _0763_ (
    .A0(\data_fifo[9][6] ),
    .A1(data_in[6]),
    .S(_0355_),
    .X(_0362_)
  );
  sky130_fd_sc_hd__buf_1 _0764_ (
    .A(_0362_),
    .X(_0114_)
  );
  sky130_fd_sc_hd__mux2_2 _0765_ (
    .A0(\data_fifo[9][7] ),
    .A1(data_in[7]),
    .S(_0355_),
    .X(_0363_)
  );
  sky130_fd_sc_hd__buf_1 _0766_ (
    .A(_0363_),
    .X(_0115_)
  );
  sky130_fd_sc_hd__nor2_2 _0767_ (
    .A(_0217_),
    .B(_0258_),
    .Y(_0364_)
  );
  sky130_fd_sc_hd__mux2_2 _0768_ (
    .A0(\data_fifo[14][0] ),
    .A1(data_in[0]),
    .S(_0364_),
    .X(_0365_)
  );
  sky130_fd_sc_hd__buf_1 _0769_ (
    .A(_0365_),
    .X(_0116_)
  );
  sky130_fd_sc_hd__mux2_2 _0770_ (
    .A0(\data_fifo[14][1] ),
    .A1(data_in[1]),
    .S(_0364_),
    .X(_0366_)
  );
  sky130_fd_sc_hd__buf_1 _0771_ (
    .A(_0366_),
    .X(_0117_)
  );
  sky130_fd_sc_hd__mux2_2 _0772_ (
    .A0(\data_fifo[14][2] ),
    .A1(data_in[2]),
    .S(_0364_),
    .X(_0367_)
  );
  sky130_fd_sc_hd__buf_1 _0773_ (
    .A(_0367_),
    .X(_0118_)
  );
  sky130_fd_sc_hd__mux2_2 _0774_ (
    .A0(\data_fifo[14][3] ),
    .A1(data_in[3]),
    .S(_0364_),
    .X(_0368_)
  );
  sky130_fd_sc_hd__buf_1 _0775_ (
    .A(_0368_),
    .X(_0119_)
  );
  sky130_fd_sc_hd__mux2_2 _0776_ (
    .A0(\data_fifo[14][4] ),
    .A1(data_in[4]),
    .S(_0364_),
    .X(_0369_)
  );
  sky130_fd_sc_hd__buf_1 _0777_ (
    .A(_0369_),
    .X(_0120_)
  );
  sky130_fd_sc_hd__mux2_2 _0778_ (
    .A0(\data_fifo[14][5] ),
    .A1(data_in[5]),
    .S(_0364_),
    .X(_0370_)
  );
  sky130_fd_sc_hd__buf_1 _0779_ (
    .A(_0370_),
    .X(_0121_)
  );
  sky130_fd_sc_hd__mux2_2 _0780_ (
    .A0(\data_fifo[14][6] ),
    .A1(data_in[6]),
    .S(_0364_),
    .X(_0371_)
  );
  sky130_fd_sc_hd__buf_1 _0781_ (
    .A(_0371_),
    .X(_0122_)
  );
  sky130_fd_sc_hd__mux2_2 _0782_ (
    .A0(\data_fifo[14][7] ),
    .A1(data_in[7]),
    .S(_0364_),
    .X(_0372_)
  );
  sky130_fd_sc_hd__buf_1 _0783_ (
    .A(_0372_),
    .X(_0123_)
  );
  sky130_fd_sc_hd__or2b_2 _0784_ (
    .A(pop),
    .B_N(push),
    .X(_0373_)
  );
  sky130_fd_sc_hd__buf_1 _0785_ (
    .A(_0373_),
    .X(_0374_)
  );
  sky130_fd_sc_hd__nor2_2 _0786_ (
    .A(count[4]),
    .B(_0374_),
    .Y(_0375_)
  );
  sky130_fd_sc_hd__or2b_2 _0787_ (
    .A(push),
    .B_N(pop),
    .X(_0376_)
  );
  sky130_fd_sc_hd__mux2_2 _0788_ (
    .A0(_0150_),
    .A1(_0375_),
    .S(_0376_),
    .X(_0377_)
  );
  sky130_fd_sc_hd__buf_1 _0789_ (
    .A(rstn),
    .X(_0378_)
  );
  sky130_fd_sc_hd__o21ai_2 _0790_ (
    .A1(count[0]),
    .A2(_0377_),
    .B1(_0378_),
    .Y(_0379_)
  );
  sky130_fd_sc_hd__a21oi_2 _0791_ (
    .A1(count[0]),
    .A2(_0377_),
    .B1(_0379_),
    .Y(_0124_)
  );
  sky130_fd_sc_hd__xor2_2 _0792_ (
    .A(count[1]),
    .B(_0374_),
    .X(_0380_)
  );
  sky130_fd_sc_hd__xnor2_2 _0793_ (
    .A(count[0]),
    .B(_0380_),
    .Y(_0381_)
  );
  sky130_fd_sc_hd__nand2_2 _0794_ (
    .A(_0377_),
    .B(_0381_),
    .Y(_0382_)
  );
  sky130_fd_sc_hd__o211a_2 _0795_ (
    .A1(count[1]),
    .A2(_0377_),
    .B1(_0382_),
    .C1(_0378_),
    .X(_0125_)
  );
  sky130_fd_sc_hd__or2_2 _0796_ (
    .A(count[2]),
    .B(_0374_),
    .X(_0383_)
  );
  sky130_fd_sc_hd__nand2_2 _0797_ (
    .A(count[2]),
    .B(_0374_),
    .Y(_0384_)
  );
  sky130_fd_sc_hd__and2_2 _0798_ (
    .A(_0383_),
    .B(_0384_),
    .X(_0385_)
  );
  sky130_fd_sc_hd__and2_2 _0799_ (
    .A(count[1]),
    .B(_0374_),
    .X(_0386_)
  );
  sky130_fd_sc_hd__a21o_2 _0800_ (
    .A1(count[0]),
    .A2(_0380_),
    .B1(_0386_),
    .X(_0387_)
  );
  sky130_fd_sc_hd__nand2_2 _0801_ (
    .A(_0385_),
    .B(_0387_),
    .Y(_0388_)
  );
  sky130_fd_sc_hd__or2_2 _0802_ (
    .A(_0385_),
    .B(_0387_),
    .X(_0389_)
  );
  sky130_fd_sc_hd__and3_2 _0803_ (
    .A(_0377_),
    .B(_0388_),
    .C(_0389_),
    .X(_0390_)
  );
  sky130_fd_sc_hd__inv_2 _0804_ (
    .A(_0377_),
    .Y(_0391_)
  );
  sky130_fd_sc_hd__and2_2 _0805_ (
    .A(count[2]),
    .B(_0391_),
    .X(_0392_)
  );
  sky130_fd_sc_hd__o21a_2 _0806_ (
    .A1(_0390_),
    .A2(_0392_),
    .B1(_0378_),
    .X(_0126_)
  );
  sky130_fd_sc_hd__xor2_2 _0807_ (
    .A(count[3]),
    .B(_0374_),
    .X(_0393_)
  );
  sky130_fd_sc_hd__a21oi_2 _0808_ (
    .A1(_0384_),
    .A2(_0388_),
    .B1(_0393_),
    .Y(_0394_)
  );
  sky130_fd_sc_hd__a31o_2 _0809_ (
    .A1(_0384_),
    .A2(_0388_),
    .A3(_0393_),
    .B1(_0391_),
    .X(_0395_)
  );
  sky130_fd_sc_hd__o221a_2 _0810_ (
    .A1(count[3]),
    .A2(_0377_),
    .B1(_0394_),
    .B2(_0395_),
    .C1(_0378_),
    .X(_0127_)
  );
  sky130_fd_sc_hd__and2_2 _0811_ (
    .A(count[4]),
    .B(_0374_),
    .X(_0396_)
  );
  sky130_fd_sc_hd__or2_2 _0812_ (
    .A(_0375_),
    .B(_0396_),
    .X(_0397_)
  );
  sky130_fd_sc_hd__o21a_2 _0813_ (
    .A1(count[3]),
    .A2(count[2]),
    .B1(_0374_),
    .X(_0398_)
  );
  sky130_fd_sc_hd__a31o_2 _0814_ (
    .A1(_0385_),
    .A2(_0387_),
    .A3(_0393_),
    .B1(_0398_),
    .X(_0399_)
  );
  sky130_fd_sc_hd__xnor2_2 _0815_ (
    .A(_0397_),
    .B(_0399_),
    .Y(_0400_)
  );
  sky130_fd_sc_hd__a22o_2 _0816_ (
    .A1(count[4]),
    .A2(_0376_),
    .B1(_0377_),
    .B2(_0400_),
    .X(_0401_)
  );
  sky130_fd_sc_hd__and2_2 _0817_ (
    .A(_0378_),
    .B(_0401_),
    .X(_0402_)
  );
  sky130_fd_sc_hd__buf_1 _0818_ (
    .A(_0402_),
    .X(_0128_)
  );
  sky130_fd_sc_hd__or2_2 _0819_ (
    .A(\ip_count[0] ),
    .B(_0216_),
    .X(_0403_)
  );
  sky130_fd_sc_hd__and3b_2 _0820_ (
    .A_N(_0237_),
    .B(_0403_),
    .C(rstn),
    .X(_0404_)
  );
  sky130_fd_sc_hd__buf_1 _0821_ (
    .A(_0404_),
    .X(_0129_)
  );
  sky130_fd_sc_hd__a21boi_2 _0822_ (
    .A1(\ip_count[1] ),
    .A2(_0237_),
    .B1_N(_0378_),
    .Y(_0405_)
  );
  sky130_fd_sc_hd__o21a_2 _0823_ (
    .A1(\ip_count[1] ),
    .A2(_0237_),
    .B1(_0405_),
    .X(_0130_)
  );
  sky130_fd_sc_hd__and3_2 _0824_ (
    .A(_0219_),
    .B(\ip_count[1] ),
    .C(_0237_),
    .X(_0406_)
  );
  sky130_fd_sc_hd__a31o_2 _0825_ (
    .A1(\ip_count[1] ),
    .A2(\ip_count[0] ),
    .A3(_0216_),
    .B1(_0219_),
    .X(_0407_)
  );
  sky130_fd_sc_hd__and3b_2 _0826_ (
    .A_N(_0406_),
    .B(_0378_),
    .C(_0407_),
    .X(_0408_)
  );
  sky130_fd_sc_hd__buf_1 _0827_ (
    .A(_0408_),
    .X(_0131_)
  );
  sky130_fd_sc_hd__a21boi_2 _0828_ (
    .A1(_0218_),
    .A2(_0406_),
    .B1_N(_0378_),
    .Y(_0409_)
  );
  sky130_fd_sc_hd__o21a_2 _0829_ (
    .A1(_0218_),
    .A2(_0406_),
    .B1(_0409_),
    .X(_0132_)
  );
  sky130_fd_sc_hd__o21a_2 _0830_ (
    .A1(push),
    .A2(_0150_),
    .B1(pop),
    .X(_0410_)
  );
  sky130_fd_sc_hd__and2_2 _0831_ (
    .A(\op_count[0] ),
    .B(_0410_),
    .X(_0411_)
  );
  sky130_fd_sc_hd__or2_2 _0832_ (
    .A(\op_count[0] ),
    .B(_0410_),
    .X(_0412_)
  );
  sky130_fd_sc_hd__and3b_2 _0833_ (
    .A_N(_0411_),
    .B(_0378_),
    .C(_0412_),
    .X(_0413_)
  );
  sky130_fd_sc_hd__buf_1 _0834_ (
    .A(_0413_),
    .X(_0133_)
  );
  sky130_fd_sc_hd__a21boi_2 _0835_ (
    .A1(\op_count[1] ),
    .A2(_0411_),
    .B1_N(rstn),
    .Y(_0414_)
  );
  sky130_fd_sc_hd__o21a_2 _0836_ (
    .A1(\op_count[1] ),
    .A2(_0411_),
    .B1(_0414_),
    .X(_0134_)
  );
  sky130_fd_sc_hd__and3_2 _0837_ (
    .A(\op_count[2] ),
    .B(\op_count[1] ),
    .C(_0411_),
    .X(_0415_)
  );
  sky130_fd_sc_hd__a31o_2 _0838_ (
    .A1(\op_count[1] ),
    .A2(\op_count[0] ),
    .A3(_0410_),
    .B1(\op_count[2] ),
    .X(_0416_)
  );
  sky130_fd_sc_hd__and3b_2 _0839_ (
    .A_N(_0415_),
    .B(rstn),
    .C(_0416_),
    .X(_0417_)
  );
  sky130_fd_sc_hd__buf_1 _0840_ (
    .A(_0417_),
    .X(_0135_)
  );
  sky130_fd_sc_hd__o21ai_2 _0841_ (
    .A1(\op_count[3] ),
    .A2(_0415_),
    .B1(_0378_),
    .Y(_0418_)
  );
  sky130_fd_sc_hd__a21oi_2 _0842_ (
    .A1(\op_count[3] ),
    .A2(_0415_),
    .B1(_0418_),
    .Y(_0136_)
  );
  sky130_fd_sc_hd__nor2b_2 _0843_ (
    .A(_0220_),
    .B_N(_0238_),
    .Y(_0419_)
  );
  sky130_fd_sc_hd__mux2_2 _0844_ (
    .A0(\data_fifo[5][0] ),
    .A1(data_in[0]),
    .S(_0419_),
    .X(_0420_)
  );
  sky130_fd_sc_hd__buf_1 _0845_ (
    .A(_0420_),
    .X(_0137_)
  );
  sky130_fd_sc_hd__mux2_2 _0846_ (
    .A0(\data_fifo[5][1] ),
    .A1(data_in[1]),
    .S(_0419_),
    .X(_0421_)
  );
  sky130_fd_sc_hd__buf_1 _0847_ (
    .A(_0421_),
    .X(_0138_)
  );
  sky130_fd_sc_hd__mux2_2 _0848_ (
    .A0(\data_fifo[5][2] ),
    .A1(data_in[2]),
    .S(_0419_),
    .X(_0422_)
  );
  sky130_fd_sc_hd__buf_1 _0849_ (
    .A(_0422_),
    .X(_0139_)
  );
  sky130_fd_sc_hd__mux2_2 _0850_ (
    .A0(\data_fifo[5][3] ),
    .A1(data_in[3]),
    .S(_0419_),
    .X(_0423_)
  );
  sky130_fd_sc_hd__buf_1 _0851_ (
    .A(_0423_),
    .X(_0140_)
  );
  sky130_fd_sc_hd__mux2_2 _0852_ (
    .A0(\data_fifo[5][4] ),
    .A1(data_in[4]),
    .S(_0419_),
    .X(_0424_)
  );
  sky130_fd_sc_hd__buf_1 _0853_ (
    .A(_0424_),
    .X(_0141_)
  );
  sky130_fd_sc_hd__mux2_2 _0854_ (
    .A0(\data_fifo[5][5] ),
    .A1(data_in[5]),
    .S(_0419_),
    .X(_0425_)
  );
  sky130_fd_sc_hd__buf_1 _0855_ (
    .A(_0425_),
    .X(_0142_)
  );
  sky130_fd_sc_hd__mux2_2 _0856_ (
    .A0(\data_fifo[5][6] ),
    .A1(data_in[6]),
    .S(_0419_),
    .X(_0426_)
  );
  sky130_fd_sc_hd__buf_1 _0857_ (
    .A(_0426_),
    .X(_0143_)
  );
  sky130_fd_sc_hd__mux2_2 _0858_ (
    .A0(\data_fifo[5][7] ),
    .A1(data_in[7]),
    .S(_0419_),
    .X(_0427_)
  );
  sky130_fd_sc_hd__buf_1 _0859_ (
    .A(_0427_),
    .X(_0144_)
  );
  sky130_fd_sc_hd__and3b_2 _0860_ (
    .A_N(_0411_),
    .B(rstn),
    .C(_0412_),
    .X(_0428_)
  );
  sky130_fd_sc_hd__buf_1 _0861_ (
    .A(_0428_),
    .X(_0145_)
  );
  sky130_fd_sc_hd__o21a_2 _0862_ (
    .A1(\op_count[1] ),
    .A2(_0411_),
    .B1(_0414_),
    .X(_0146_)
  );
  sky130_fd_sc_hd__and3b_2 _0863_ (
    .A_N(_0415_),
    .B(rstn),
    .C(_0416_),
    .X(_0429_)
  );
  sky130_fd_sc_hd__buf_1 _0864_ (
    .A(_0429_),
    .X(_0147_)
  );
  sky130_fd_sc_hd__a21oi_2 _0865_ (
    .A1(\op_count[3] ),
    .A2(_0415_),
    .B1(_0418_),
    .Y(_0148_)
  );
  sky130_fd_sc_hd__dfxtp_2 _0866_ (
    .CLK(clk),
    .D(_0004_),
    .Q(\data_fifo[6][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0867_ (
    .CLK(clk),
    .D(_0005_),
    .Q(\data_fifo[6][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0868_ (
    .CLK(clk),
    .D(_0006_),
    .Q(\data_fifo[6][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0869_ (
    .CLK(clk),
    .D(_0007_),
    .Q(\data_fifo[6][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0870_ (
    .CLK(clk),
    .D(_0008_),
    .Q(\data_fifo[6][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0871_ (
    .CLK(clk),
    .D(_0009_),
    .Q(\data_fifo[6][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0872_ (
    .CLK(clk),
    .D(_0010_),
    .Q(\data_fifo[6][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0873_ (
    .CLK(clk),
    .D(_0011_),
    .Q(\data_fifo[6][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0874_ (
    .CLK(clk),
    .D(_0012_),
    .Q(\data_fifo[1][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0875_ (
    .CLK(clk),
    .D(_0013_),
    .Q(\data_fifo[1][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0876_ (
    .CLK(clk),
    .D(_0014_),
    .Q(\data_fifo[1][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0877_ (
    .CLK(clk),
    .D(_0015_),
    .Q(\data_fifo[1][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0878_ (
    .CLK(clk),
    .D(_0016_),
    .Q(\data_fifo[1][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0879_ (
    .CLK(clk),
    .D(_0017_),
    .Q(\data_fifo[1][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0880_ (
    .CLK(clk),
    .D(_0018_),
    .Q(\data_fifo[1][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0881_ (
    .CLK(clk),
    .D(_0019_),
    .Q(\data_fifo[1][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0882_ (
    .CLK(clk),
    .D(_0020_),
    .Q(\data_fifo[15][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0883_ (
    .CLK(clk),
    .D(_0021_),
    .Q(\data_fifo[15][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0884_ (
    .CLK(clk),
    .D(_0022_),
    .Q(\data_fifo[15][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0885_ (
    .CLK(clk),
    .D(_0023_),
    .Q(\data_fifo[15][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0886_ (
    .CLK(clk),
    .D(_0024_),
    .Q(\data_fifo[15][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0887_ (
    .CLK(clk),
    .D(_0025_),
    .Q(\data_fifo[15][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0888_ (
    .CLK(clk),
    .D(_0026_),
    .Q(\data_fifo[15][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0889_ (
    .CLK(clk),
    .D(_0027_),
    .Q(\data_fifo[15][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0890_ (
    .CLK(clk),
    .D(_0028_),
    .Q(\data_fifo[12][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0891_ (
    .CLK(clk),
    .D(_0029_),
    .Q(\data_fifo[12][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0892_ (
    .CLK(clk),
    .D(_0030_),
    .Q(\data_fifo[12][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0893_ (
    .CLK(clk),
    .D(_0031_),
    .Q(\data_fifo[12][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0894_ (
    .CLK(clk),
    .D(_0032_),
    .Q(\data_fifo[12][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0895_ (
    .CLK(clk),
    .D(_0033_),
    .Q(\data_fifo[12][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0896_ (
    .CLK(clk),
    .D(_0034_),
    .Q(\data_fifo[12][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0897_ (
    .CLK(clk),
    .D(_0035_),
    .Q(\data_fifo[12][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0898_ (
    .CLK(clk),
    .D(_0036_),
    .Q(\data_fifo[13][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0899_ (
    .CLK(clk),
    .D(_0037_),
    .Q(\data_fifo[13][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0900_ (
    .CLK(clk),
    .D(_0038_),
    .Q(\data_fifo[13][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0901_ (
    .CLK(clk),
    .D(_0039_),
    .Q(\data_fifo[13][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0902_ (
    .CLK(clk),
    .D(_0040_),
    .Q(\data_fifo[13][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0903_ (
    .CLK(clk),
    .D(_0041_),
    .Q(\data_fifo[13][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0904_ (
    .CLK(clk),
    .D(_0042_),
    .Q(\data_fifo[13][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0905_ (
    .CLK(clk),
    .D(_0043_),
    .Q(\data_fifo[13][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0906_ (
    .CLK(clk),
    .D(_0044_),
    .Q(\data_fifo[2][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0907_ (
    .CLK(clk),
    .D(_0045_),
    .Q(\data_fifo[2][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0908_ (
    .CLK(clk),
    .D(_0046_),
    .Q(\data_fifo[2][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0909_ (
    .CLK(clk),
    .D(_0047_),
    .Q(\data_fifo[2][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0910_ (
    .CLK(clk),
    .D(_0048_),
    .Q(\data_fifo[2][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0911_ (
    .CLK(clk),
    .D(_0049_),
    .Q(\data_fifo[2][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0912_ (
    .CLK(clk),
    .D(_0050_),
    .Q(\data_fifo[2][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0913_ (
    .CLK(clk),
    .D(_0051_),
    .Q(\data_fifo[2][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0914_ (
    .CLK(clk),
    .D(_0052_),
    .Q(\data_fifo[10][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0915_ (
    .CLK(clk),
    .D(_0053_),
    .Q(\data_fifo[10][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0916_ (
    .CLK(clk),
    .D(_0054_),
    .Q(\data_fifo[10][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0917_ (
    .CLK(clk),
    .D(_0055_),
    .Q(\data_fifo[10][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0918_ (
    .CLK(clk),
    .D(_0056_),
    .Q(\data_fifo[10][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0919_ (
    .CLK(clk),
    .D(_0057_),
    .Q(\data_fifo[10][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0920_ (
    .CLK(clk),
    .D(_0058_),
    .Q(\data_fifo[10][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0921_ (
    .CLK(clk),
    .D(_0059_),
    .Q(\data_fifo[10][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0922_ (
    .CLK(clk),
    .D(_0060_),
    .Q(\data_fifo[11][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0923_ (
    .CLK(clk),
    .D(_0061_),
    .Q(\data_fifo[11][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0924_ (
    .CLK(clk),
    .D(_0062_),
    .Q(\data_fifo[11][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0925_ (
    .CLK(clk),
    .D(_0063_),
    .Q(\data_fifo[11][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0926_ (
    .CLK(clk),
    .D(_0064_),
    .Q(\data_fifo[11][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0927_ (
    .CLK(clk),
    .D(_0065_),
    .Q(\data_fifo[11][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0928_ (
    .CLK(clk),
    .D(_0066_),
    .Q(\data_fifo[11][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0929_ (
    .CLK(clk),
    .D(_0067_),
    .Q(\data_fifo[11][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0930_ (
    .CLK(clk),
    .D(_0068_),
    .Q(\data_fifo[0][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0931_ (
    .CLK(clk),
    .D(_0069_),
    .Q(\data_fifo[0][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0932_ (
    .CLK(clk),
    .D(_0070_),
    .Q(\data_fifo[0][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0933_ (
    .CLK(clk),
    .D(_0071_),
    .Q(\data_fifo[0][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0934_ (
    .CLK(clk),
    .D(_0072_),
    .Q(\data_fifo[0][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0935_ (
    .CLK(clk),
    .D(_0073_),
    .Q(\data_fifo[0][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0936_ (
    .CLK(clk),
    .D(_0074_),
    .Q(\data_fifo[0][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0937_ (
    .CLK(clk),
    .D(_0075_),
    .Q(\data_fifo[0][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0938_ (
    .CLK(clk),
    .D(_0076_),
    .Q(\data_fifo[3][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0939_ (
    .CLK(clk),
    .D(_0077_),
    .Q(\data_fifo[3][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0940_ (
    .CLK(clk),
    .D(_0078_),
    .Q(\data_fifo[3][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0941_ (
    .CLK(clk),
    .D(_0079_),
    .Q(\data_fifo[3][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0942_ (
    .CLK(clk),
    .D(_0080_),
    .Q(\data_fifo[3][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0943_ (
    .CLK(clk),
    .D(_0081_),
    .Q(\data_fifo[3][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0944_ (
    .CLK(clk),
    .D(_0082_),
    .Q(\data_fifo[3][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0945_ (
    .CLK(clk),
    .D(_0083_),
    .Q(\data_fifo[3][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0946_ (
    .CLK(clk),
    .D(_0084_),
    .Q(\data_fifo[8][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0947_ (
    .CLK(clk),
    .D(_0085_),
    .Q(\data_fifo[8][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0948_ (
    .CLK(clk),
    .D(_0086_),
    .Q(\data_fifo[8][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0949_ (
    .CLK(clk),
    .D(_0087_),
    .Q(\data_fifo[8][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0950_ (
    .CLK(clk),
    .D(_0088_),
    .Q(\data_fifo[8][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0951_ (
    .CLK(clk),
    .D(_0089_),
    .Q(\data_fifo[8][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0952_ (
    .CLK(clk),
    .D(_0090_),
    .Q(\data_fifo[8][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0953_ (
    .CLK(clk),
    .D(_0091_),
    .Q(\data_fifo[8][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0954_ (
    .CLK(clk),
    .D(_0092_),
    .Q(\data_fifo[7][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0955_ (
    .CLK(clk),
    .D(_0093_),
    .Q(\data_fifo[7][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0956_ (
    .CLK(clk),
    .D(_0094_),
    .Q(\data_fifo[7][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0957_ (
    .CLK(clk),
    .D(_0095_),
    .Q(\data_fifo[7][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0958_ (
    .CLK(clk),
    .D(_0096_),
    .Q(\data_fifo[7][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0959_ (
    .CLK(clk),
    .D(_0097_),
    .Q(\data_fifo[7][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0960_ (
    .CLK(clk),
    .D(_0098_),
    .Q(\data_fifo[7][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0961_ (
    .CLK(clk),
    .D(_0099_),
    .Q(\data_fifo[7][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0962_ (
    .CLK(clk),
    .D(_0100_),
    .Q(\data_fifo[4][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0963_ (
    .CLK(clk),
    .D(_0101_),
    .Q(\data_fifo[4][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0964_ (
    .CLK(clk),
    .D(_0102_),
    .Q(\data_fifo[4][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0965_ (
    .CLK(clk),
    .D(_0103_),
    .Q(\data_fifo[4][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0966_ (
    .CLK(clk),
    .D(_0104_),
    .Q(\data_fifo[4][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0967_ (
    .CLK(clk),
    .D(_0105_),
    .Q(\data_fifo[4][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0968_ (
    .CLK(clk),
    .D(_0106_),
    .Q(\data_fifo[4][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0969_ (
    .CLK(clk),
    .D(_0107_),
    .Q(\data_fifo[4][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0970_ (
    .CLK(clk),
    .D(_0108_),
    .Q(\data_fifo[9][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0971_ (
    .CLK(clk),
    .D(_0109_),
    .Q(\data_fifo[9][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0972_ (
    .CLK(clk),
    .D(_0110_),
    .Q(\data_fifo[9][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0973_ (
    .CLK(clk),
    .D(_0111_),
    .Q(\data_fifo[9][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0974_ (
    .CLK(clk),
    .D(_0112_),
    .Q(\data_fifo[9][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0975_ (
    .CLK(clk),
    .D(_0113_),
    .Q(\data_fifo[9][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0976_ (
    .CLK(clk),
    .D(_0114_),
    .Q(\data_fifo[9][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0977_ (
    .CLK(clk),
    .D(_0115_),
    .Q(\data_fifo[9][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0978_ (
    .CLK(clk),
    .D(_0116_),
    .Q(\data_fifo[14][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0979_ (
    .CLK(clk),
    .D(_0117_),
    .Q(\data_fifo[14][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0980_ (
    .CLK(clk),
    .D(_0118_),
    .Q(\data_fifo[14][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0981_ (
    .CLK(clk),
    .D(_0119_),
    .Q(\data_fifo[14][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0982_ (
    .CLK(clk),
    .D(_0120_),
    .Q(\data_fifo[14][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0983_ (
    .CLK(clk),
    .D(_0121_),
    .Q(\data_fifo[14][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0984_ (
    .CLK(clk),
    .D(_0122_),
    .Q(\data_fifo[14][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0985_ (
    .CLK(clk),
    .D(_0123_),
    .Q(\data_fifo[14][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0986_ (
    .CLK(clk),
    .D(_0124_),
    .Q(count[0])
  );
  sky130_fd_sc_hd__dfxtp_2 _0987_ (
    .CLK(clk),
    .D(_0125_),
    .Q(count[1])
  );
  sky130_fd_sc_hd__dfxtp_2 _0988_ (
    .CLK(clk),
    .D(_0126_),
    .Q(count[2])
  );
  sky130_fd_sc_hd__dfxtp_2 _0989_ (
    .CLK(clk),
    .D(_0127_),
    .Q(count[3])
  );
  sky130_fd_sc_hd__dfxtp_2 _0990_ (
    .CLK(clk),
    .D(_0128_),
    .Q(count[4])
  );
  sky130_fd_sc_hd__dfxtp_2 _0991_ (
    .CLK(clk),
    .D(_0129_),
    .Q(\ip_count[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0992_ (
    .CLK(clk),
    .D(_0130_),
    .Q(\ip_count[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0993_ (
    .CLK(clk),
    .D(_0131_),
    .Q(\ip_count[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0994_ (
    .CLK(clk),
    .D(_0132_),
    .Q(\ip_count[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0995_ (
    .CLK(clk),
    .D(_0133_),
    .Q(\op_count[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0996_ (
    .CLK(clk),
    .D(_0134_),
    .Q(\op_count[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0997_ (
    .CLK(clk),
    .D(_0135_),
    .Q(\op_count[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0998_ (
    .CLK(clk),
    .D(_0136_),
    .Q(\op_count[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _0999_ (
    .CLK(clk),
    .D(_0137_),
    .Q(\data_fifo[5][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1000_ (
    .CLK(clk),
    .D(_0138_),
    .Q(\data_fifo[5][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1001_ (
    .CLK(clk),
    .D(_0139_),
    .Q(\data_fifo[5][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1002_ (
    .CLK(clk),
    .D(_0140_),
    .Q(\data_fifo[5][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1003_ (
    .CLK(clk),
    .D(_0141_),
    .Q(\data_fifo[5][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1004_ (
    .CLK(clk),
    .D(_0142_),
    .Q(\data_fifo[5][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1005_ (
    .CLK(clk),
    .D(_0143_),
    .Q(\data_fifo[5][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1006_ (
    .CLK(clk),
    .D(_0144_),
    .Q(\data_fifo[5][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1007_ (
    .CLK(clk),
    .D(_0145_),
    .Q(_0000_)
  );
  sky130_fd_sc_hd__dfxtp_2 _1008_ (
    .CLK(clk),
    .D(_0146_),
    .Q(_0001_)
  );
  sky130_fd_sc_hd__dfxtp_2 _1009_ (
    .CLK(clk),
    .D(_0147_),
    .Q(_0002_)
  );
  sky130_fd_sc_hd__dfxtp_2 _1010_ (
    .CLK(clk),
    .D(_0148_),
    .Q(_0003_)
  );
endmodule
